### ISSUE TITLE
Ansibalisatie Verne, Clarke & Wells

### ISSUE THREAD

**Issue by rien** [ZeusWPI/ansible-config#75]
Verne doet raar met schijven enzo, dus plaatsen we best alles in een software i.p.v. hardware raid.
We gingen Verne opnieuw 'opbouwen', maar dan op Zeven. Ondertussen plaatsen we alles in Ansible.

Deze issue is vooral om een lijstje bij te houden van wat er allemaal moet gebeuren en eventueel wat dingen te bespreken over hoe we alles het best aanpakken.

~~Ik stel ook voor om al deze servers op Arch te laten draaien i.p.v. Debian. heeft er hier iemand problemen mee?~~ We blijven gewoon bij Debian voor Clarke en Verne.
## TODO:

(Vul gerust aan)
### Verne
- [ ] Instellen als router (dnsmasq, arno, network, ...) 
- [ ] UFW ipv Arno
- [ ] Xenserver (met Clarke en Wells)
### Clarke
- [ ] Nginx
- [ ] Kerberos
- [ ] OAuth
### Wells
- [ ] Inloggen met Kerberos
- [ ] Userdirs (gewoon `/home` ipv AFS zeker?)
- [ ] Webspace voor users

**Comment by nudded** [comment]
-1 voor servers op Arch te laten draaien. Voor Wells is het wel OK. Als je toch een andere machine gaat gebruiken, zonder Xen, hoef je ook niet verne en clarke te scheiden.

Maar zet verne en clarke gewoon op debian (of moeste echt willen, 16.04.1 LTS)

**Comment by nudded** [comment]
ik zou eens kijken naar UFW voor de firewall. blijkbaar wordt die meer gebruikt.

**Comment by R13N** [comment]
Waarom geen arch op clarke en verne? Ik heb persoonlijk weinig problemen gehad met arch op mijn servers. Het grootste probleem dat ik heb met debian is dat bij de grote updates ( 7 -> 8 ) dingen kapotgaan. + arch kan beter omgaan met 'experimentelere' software, wat we af en toe gebruiken op onze servers.

UFW ziet er qua configuratie ook simpeler uit. Ik zal er zeker eens naar kijken.

**Comment by redfast00** [comment]
Al die machines zijn dood
